travis:
  secure:
    BINSTAR_TOKEN: lpaCAeuSaKlBSyyrX5BCK5v2/hfAN/cIv+ka+yQEJgiJ9CV6fbm6/dlkBJ30WPwQZeUKXaJARKJNUjbQ2pO5ae9OJjaqmPqn+AnKzSW8Ix6hJ/RNW1lpLmvgXy9ocNhaxM4gtAbqr63ndOJxpU5BcW7ixk2AANtu8hOWbQepoMfxzSyfygfx1qdqGMBBOVVgdiOFlEzZiKij6LiLLhsR82+f3wKCILLbaaHgPx+JMMXU6l6XG6+9TAgLghX8CcVAyOk3y7LX9sCbQrfpzsWBWLqWH8zdD4vZPZ1CwAqcjGpbPXJAaYiMxCp2Wq/TdKfia7QKsmmv4i4yISfhut9oJvDySlDIaii2Q8ivyM471kMspHpaSwswwWeMhoENMtFomuUvfavmd3tLQnWPW6V4YUxXiEbsbUHsH2LD97WLNo9POSiFxOloxjJEmjk5ejDccQXKr9TjiEsTtr31D5h0+VL8VtUFwiwYC4hERiz4CME7ruVrjBBjFgrpC8cWLS0osM91763tynQFh2AMDleOIAnU8IiNk5MLKN7x1/tLKkESXtJFpdY4tkHqaa5a3H/ZGVEZKgbh4Qqhok0pKd3V/bY2ot6H1ezeoABzZ0yol0cgHCEXHhFK3BBky1f5h5tG2OqALoRnF1P+X2GyFmi7Y9V/w5XVyRg2idCukJ5umEQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
